### ISSUE TITLE
啥时候发布新的 pypi 啊...

### ISSUE THREAD

**Issue by tonicbupt** [eleme/ruskit#47]
前几天在 `FLUSHALL` 的时候去尝试连接发现挂了, 因为代码会去 `PING`, 那个数据库很大, `FLUSHALL` 要一点时间的. 然后就发现... 为啥仓库里最新的代码没有 `PING`!!! 一看发现 pypi 上的是 0.0.7, github 都 0.0.22 了... 😿  啥时候发布个更新啊... 感恩各位爸爸...

**Comment by doyoubi** [comment]
好了

**Comment by tonicbupt** [comment]
👍  感谢!
